# NumPy Eğitim Notları

<p>Merhaba. Bu defterde NumPy kütüphanesinin kullanımını anlatacağım.
NumPy veri bilimi için kullanılan temel bir kütüphanedir ve veri biliminde
başlangıç olarak bu kütüphane öğrenilir.</p> <p>Bu eğitimde Numpy kütüphanesinin nasıl kullanıldığını anlatan temel düzeyde eğitici bilgiler yazdım. Ben bu kütüphaneyi örenirken bu defteri yazdım ve faydalı olması
açısından github sayfamda yayınladım.
Bu eğitim notları, Python bildiğiniz var sayılarak anlatılmıştır. Bu defterde Python eğitimi bulunmamaktadır.</p>

<a href="https://www.github.com/YigitC7">Github<a>

<br>

<p>Hadi başlayalım :)</p>

In [2]:
import numpy as np # Dahil ettik ve np olarak yeniden isimlendirdik

## Fonksiyonlar

### array fonksiyonu ve matrixler

In [4]:
# Bu fonksiyon parametre olarak içerisine liste alır ve bu liste NumPy ile işlem yapabileceğimiz farklı bir liste formatına dönüştürülür.
# Örnek:

liste = [1,2,3,4,5,6,7]
np.array(liste)

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# Görmüş olduğunuz üzere liste değişkenine bağlı olan bir liste verisini NumPy kütüphanesinin işlem yapabileceği bir forma dönüştürdük.
# Şimdi de bunun tipine bir bakalım:

print(type(np.array(liste)))

<class 'numpy.ndarray'>


In [6]:
# Ve tabiki bunu da bir değişkene atayabiliriz.

YeniListe = np.array(liste)
YeniListe # Bunu yaparak listenin içeriğini görüntüleyebiliriz.

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# Şimdi Matrix bir liste oluşturalim :D Ama matrix liste de nedir? İşte bir örnek:

MatrixListe = [[1,2,3,4,5],[6,7,8,9,0]]

# İşte bu bir matrix listedir, yani iki boyutlu bir liste.
# Aklınızdaki soru şu olmalı, Bu listenin elemanlarına nasıl erişebilirim?
# İşte şu şekilde:

print(MatrixListe[1][2]) # Birinci index'de ki liste ve o liste'de ki ikinci index'de ki eleman. Çıktı:

8


In [14]:
# [1][2]:
# [1] --> [[1,2,3,4,5],[6,7,8,9,0]]
#                       ^ 1 index'te ki liste
# [2] --> [6,7,8,9,0]
#              ^ 2 index'te ki eleman

# Sadece bir tane index girersek ne olur?

print(MatrixListe[1])

[6, 7, 8, 9, 0]


In [11]:
# Gürmüş olduğunuz gibi birinci index'de olan listenin tamamını verdi (Bunu tahmin edenler Python bilgileri gelişmiştir)
# Şimdi bu Matrix Listeyi array fonksiyonu ile dönüştürelim:

YeniMatrixListe = np.array(MatrixListe)

In [12]:
# Bu Listeyi görüntüleyelim

YeniMatrixListe

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [1]:
# Görmüş olduğunuz gibi listeyi 2 boyutlu bir şekilde, yani daha düzenli bir şekilde görüntüleyebiliyoruz.

### arange fonksiyonu

In [5]:
# Bu fonksiyon tıpkı range gibi sayılar üretir.
# Örnek:

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 1'den 10'a kadar sayı üretti ama 10 dahil değil.
# Şimdi de ikişer olarak gidelim (2'den 20'e ikişer ikişer gitsin):

np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
# Bunun mantığı bildiğiniz range() fonksiyonu gibidir.

### zeros ve ones fonksiyonları

In [16]:
# Bu iki fonksiyon aynı şekilde çalıştığı için ikisini bir başlıkta ele almak mantıklıdır.
# zeros fonksiyonu sadece 0 sayılar üretirken ones fonksiyonu ise sadece 1 sayılar üretir.
# önce zeros fonksiyonuna bir bakalım:

np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# 8 tane sıfırlardan oluşan bir liste verdi.
# Peki bunu iki boyutlu yapabilirmiyiz? bir deniyelim:

np.zeros(8,8)

TypeError: Cannot interpret '8' as a data type

In [19]:
# Hata verdi, bunun nedeni şudur, eğer bu fonksiyonda iki boyutlu bir liste üreteceksek o zaman iki kat () koymalıyız.
# Örnek:

np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# İşte oldu :D 8x8 büyüklüğünde iki boyutlu ve sadece sıfırlar ile oluşan bir liste yaptık.

# Şimdi de ones fonksiyonuna bakalım
# Bu fonksiyonda tıpkı zeros fonksiyonu gibidir ama tek farkı, sıfır yerine bir sayılarını üretmesi
# Örnek:

np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### linspace fonksiyonu

In [25]:
# Bu fonksiyon veri biliminde sik kullanılan ve önemli bir fonksiyondur. Peki ne işe yarar?
# arange fonksiyonu gibi sayılar üretir ama en büyük farkı ise, ürettüğünüz sayının mesafesini istediğiniz kadar arttırabilirsiniz.
# Bu fonksiyon 3 tane int değer alabilir ama üçüncü zorumlu değil.


np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
# Burada yaptığımız şey şu, 1'den 10'a kadar giden 10 tane sayı ürettik. Bu sayıların mesafesi hep aynı olacaktır.
# Peki 1'den 10'a kadar giden 20 sayı üret dersek ne olur?

np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [27]:
# Bu sefer fluat tipine geçti ve 10'a gidene kadar 20 tane sayı üretti ama hepsinin arasında eşit farklar var.
# 1 ve 10 dışında hepsi fluat tipindedir.
# Mesafeyi istediğiniz kadar arttırabilirsiniz.

np.linspace(1,10,40)

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

### eye fonksiyonu

In [33]:
# Bu fonksiyon pek gerekli görünmüyor ama belki işe yarayabilir.
# Bu fonksiyon ise, desenli bir biçimde bir ve sıfırlardan oluşan iki boyutlu bir liste üretir
# Örnek:

np.eye(3) # 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(10) # 10x10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Random kütüphanesi

In [35]:
# Bu kütüphane np'nin altındadır ve iki tane fonksiyondan bahsedeceğim, randn ve randint.

# randn:
# Hem tek boyutlu hemde iki boutlu olacak şekilde rastgele sayılardan oluşan liste üretir.
# Ama üreteceğimiz sayıların aralığını belirleyemeyiz.
# Örnek:

np.random.randn(8) # Tek boyutlu

array([-0.08843831,  0.00565588, -0.43474202,  0.23854244,  0.43838438,
        2.23702243,  0.45775355,  0.07786934])

In [36]:
np.random.randn(8,8) # İki boyutlu

array([[ 1.98351773, -0.40509379, -2.12357139,  0.73276429, -0.53688756,
        -0.29127005, -1.73726265, -0.01310573],
       [ 1.20906203, -1.41490795, -1.28212023,  0.23510146, -1.42494921,
         3.26779702, -0.69905664,  0.66632368],
       [-1.09346219, -0.82979531, -0.49241007,  2.21479496,  1.27480928,
         1.1251428 ,  0.35174174,  0.97480863],
       [-1.23420722,  0.92259915,  2.43442114,  1.51980964,  0.97128398,
         0.07521105, -0.82639453,  0.63232158],
       [-0.65761281, -0.09005304,  1.6638285 ,  1.45829453,  0.46203928,
        -0.3140789 ,  0.34936266,  0.60011712],
       [ 0.33638693,  0.87992121, -1.24463934,  0.08456173,  0.0225444 ,
         2.38053762, -1.88551741,  0.01578147],
       [-1.8136862 ,  3.19093183,  1.41114709, -0.33809315,  0.04251555,
         0.73014823,  0.23960607, -0.34898826],
       [-1.75623561,  0.70395775, -1.58570664,  0.67692891,  0.96538739,
         1.82039506, -1.24235901,  0.0891461 ]])

In [49]:
# randint:
# Bu fonksiyon ise bildiğiniz randint gibi çalışır.

np.random.randint(1,7) # 1'den 7'ye kadar rastgele sayı üret ama 7 dahil değil.

6

In [52]:
# Üçüncü bir parametre girersek liste oluşturacak ve üçüncü parametre kadar rastgele sayı üretir

np.random.randint(1,7,10)

array([6, 3, 2, 2, 2, 1, 3, 5, 3, 3])

In [1]:
# 10 tane 1'den 7'ye kadar (7 dahil değil) 10 tane rastgele sayı ürettik.
# Bu foksiyon sadece tek boyutludur ama for döngüsü ile iki boyutlu olacak şekilde yapabilirsiniz.

## Methodlar

### reshape hethodu

In [9]:
# Bu Method bir listeyi iki boyutla hale getirir ve listeyi böler.
# Örnek:

Liste = np.random.randint(1,10,40) # 40 elemanlık rastgele sayılardan oluşan bir listemiz var, şimdi bunu Matrix bir listeye dönüştürelim.
Liste # İçeriğine bir bakalım

array([1, 3, 3, 9, 5, 9, 7, 3, 2, 4, 9, 5, 3, 7, 2, 8, 3, 3, 7, 9, 9, 9,
       4, 4, 3, 2, 7, 2, 4, 7, 9, 4, 7, 3, 5, 9, 5, 8, 6, 1])

In [16]:
# Şimdi bunu ikinci boyuta dönüştürelim:

Liste.reshape(4,10)

array([[1, 3, 3, 9, 5, 9, 7, 3, 2, 4],
       [9, 5, 3, 7, 2, 8, 3, 3, 7, 9],
       [9, 9, 4, 4, 3, 2, 7, 2, 4, 7],
       [9, 4, 7, 3, 5, 9, 5, 8, 6, 1]])

In [17]:
# İşte burada listeyi iki boyutlu olacak şekilde böldük.
# Eğer uyuşmayan bir bölme biçimi girseydik hata alırdık.

Liste.reshape(5,6)

ValueError: cannot reshape array of size 40 into shape (5,6)

In [18]:
# Bu method sayesinde listelerimizi bölebilir ve bu sayede daha iyi okunabilir hale getirebiliriz.

### max ve min methodları

In [19]:
# max methodu listede bulunan en büyük değeri getirirken min ise en küçük elemanı, yani sayıyı getirir.
# Örnek: (Yukarıda oluşturduğumuz List değşkeninini kullanalım)

Liste.max()

9

In [20]:
# Max 9 olması beklendik bir durum çünkü bu listeyi 1'den 10'a kadar ama 10 dahil olmayacak şekilde random sayı üretmesini istedik.
# Şimdi de minimum, yani bu listede bulunan en küçük elemanını bularım, ki onu zaten biliyoruz.

Liste.min()

1

### argmax ve argmin methodları

In [21]:
# Max ve Min methodlarının yaptığı işi yapar, en büyük ve en küçük değerini bize verir ama bu sefer sadece bu dğerlerin index numarasını bize verir.
# Yani max değeri bulur ve bu sefer sadece index numarasını yazar.
# Örnek:

Liste.argmax() 

3

In [24]:
# Demekki max değer olan 9 elemanı ilk defa 3.index'de (bu liste rastgele değerlerden oluştuğu için, siz tekrar başlatınca farklı indexler görünebilir)
# bulunuyor, bir bakalım:

Liste

array([1, 3, 3, 9, 5, 9, 7, 3, 2, 4, 9, 5, 3, 7, 2, 8, 3, 3, 7, 9, 9, 9,
       4, 4, 3, 2, 7, 2, 4, 7, 9, 4, 7, 3, 5, 9, 5, 8, 6, 1])

In [25]:
# Şimdi de minimum değerin index numarasına bakalım

Liste.argmin()

0

### shape methodu

In [27]:
# 1 yada 2 boyutlu bir listenin boyutunu verir.
# Bir listeyi iki boyutlu yapıp bu methodu kullanınca daha iyi anlarsınız:

MatrixListe = Liste.reshape(4,10) # Yine yukarıdaki Listeyi kullandım (sjsjsj)
MatrixListe

array([[1, 3, 3, 9, 5, 9, 7, 3, 2, 4],
       [9, 5, 3, 7, 2, 8, 3, 3, 7, 9],
       [9, 9, 4, 4, 3, 2, 7, 2, 4, 7],
       [9, 4, 7, 3, 5, 9, 5, 8, 6, 1]])

In [29]:
# Şimdi bunun boyutuna bakalım

MatrixListe.shape

(4, 10)

In [30]:
# Görmüş olduğunuz gibi bu listenin 4x10 boytunda olduğunu bize söyledi
# Şimdi de tek boyutlu bie listeyi deniyelim:

Liste.shape

(40,)

In [31]:
# Tek boyutlu liste olduğu için sadece bir eleman verdi ve bu da listenin kaç elemanlı olduğunu gösteriyor.
# Yani tek boyutda bu method len fonksiyonu gibi çalışır.

print(len(Liste))

40


## İndex işlemleri

### Bir boyutlu listeler

In [6]:
# Bir boyutlu listelerde index işlemleri yapacağız, önce 0'dan 15'e kadar(Yani 14) bir liste oluşturalım

Liste = np.arange(0,15)
Liste

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
# Şimdi 8.index'de bulunan elemanı görelim

Liste[8]

8

In [8]:
# Bu kadar basit :D
# Şimdi de 0'dan 8'e kadar(8 yine dahil değil) olan verileri görüntüleyelim

Liste[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
# Bu işlemleri zaten biliyorsunuz, python'da yaptığımız sıradan işlemler. Şimdi farklı birşey yapalım.
# Belirlediğimiz index'de ki elemanları değiştirelim:

Liste[1:6] = 0

# Bir bakalım
Liste

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# 1'den 6'ya kadar yani 5'e kadar, artık her neyse, bu indexleri 0'a çevirdik.
# Şimdi çok garip birşey yapalım, bu indexleri bir değişkene atayalım ve değiştirelim

Liste = np.arange(0,15) # Eski haline çevirme
Liste2 = Liste[1:8] # Bu indexleri farklı bir değişkene atamak

# eee bunun neresi garip? şimdi göreceksiniz...

# Liste2 Çıktı:
Liste2

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Liste çıktı:
Liste

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# Evet iki ayrı liste elde ettik, şimdi Liste2'de ki bütün elemanları değiştirelim.
# Bütün elemanları seçmek için [:] yazmak yeterli

Liste2[:] = -8

# Bakalım
Liste2

array([-8, -8, -8, -8, -8, -8, -8])

In [20]:
# Şimdi gerip olan şeyi göstereyim.
# İki ayrı liste ürettik ve ben sadece bu listeyi değiştirdim
# Liste değişkeninin sabit olduğunu düşünebilirsiniz ama bir bakalım:

Liste

array([ 0, -8, -8, -8, -8, -8, -8, -8,  8,  9, 10, 11, 12, 13, 14])

In [28]:
# Bu nasıl olur? ben sadece List2'yi değiştirdim bu nasıl olur?
# İlk başta bende anlamamıştım ama biraz düşününce bunun neden olduğunu anlayabiliyoruz.
# Gerçek python programcıları iseniz o zaman bunun neyden kaynaklandığını anlamış olmalısınız.

# Biz dedik ki Liste2 = Liste[1:8] Yani burada yeni bir liste oluşturmuyoruz.
# Sadece bu listede bulunan, çağırdığımız indexleri bir değişkene atamış oluyoruz.
# Yani Liste2 aslında bir liste değil, o sadece Liste'nin belirli elemanlarını tutan bir değişken.
# Liste[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
#         ^^^^^^^^^^^^^ = Liste2
# List2[:] = -8 | sonuç:
# Liste[0,-8,-8,-8,-8,-8,-8,-8,8,9,10,11,12,13,14]
#         ^^^^^^^^^^^^^^^^^^^^ = Liste2

# Eğer istediğiniz index'de ki elemanları gerçek bir liste halinde olmasını istiyorsak o zaman copy methodunu kullanırız.
# Yani listenin kopyasını oluşturacağız, ondan sonra istediğimiz index'i alır gibi yapacağız
# Örnek:

Liste = np.arange(0,15) # Listeyi eski haline getir
ListeKopyasi = Liste.copy() # Listeyi kopyala

Liste

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
ListeKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
# Listeyi kopyaladık, şimdi orjinalini değiştirmeden istediğimiz index'de ki verileri değiştirebiliriz.

Liste2 = ListeKopyasi[1:8]
Liste2[:] = 0

Liste2

array([0, 0, 0, 0, 0, 0, 0])

In [32]:
Liste

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
ListeKopyasi

array([ 0,  0,  0,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

## İki boyutlu listeler

In [35]:
# Bu seferde iki boyutlu, yani matrix olan listeler üzerinden index işlemleri yapacağız.
# Öncelikle 2D bir liste oluşturalım

MatrixListe = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
MatrixListe

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# Bunun iki tane erişim parametresi vardır
# birinci parametre listeyi seçer ve ikinci parametre seçilen listedeki elemanı seçer.
# Örnek olarak ikinci index'de bulunan listenin 0.index'de ki elemanını istiyelim

MatrixListe[2][0]

7

In [39]:
# Bu kadar basir aslında

# İlk parametre [2]:
# [1, 2, 3] 0.index
# [4, 5, 6] 1.index
# [7, 8, 9] 2.index <

# İkinci parametre [0]:
# [7, 8, 9]
#  ^ 

# iki tane [][] kullanmak yerine şu şekilde de kullanılabilir: [2,0]

MatrixListe[2,0]

7

In [41]:
# Birden fazla liste seçersek ne olur?

MatrixListe[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# 0'dan 2'ye kadar ama 2 dahil değil

# [1, 2, 3] 0.index <
# [4, 5, 6] 1.index <
# [7, 8, 9] 2.index

# Birde şöyle birşey yapalım

MatrixListe[0:2,0]

array([1, 4])

In [43]:
# Bu sefer ise 0 ve 1 index'de bulunan listeleri seçti ve bu iki listenin 0.index'de bulunan elemanını bize verdi.
# Bu sefer şunu yapalım: bütün listelerde bulunan elemanların 1.index'de ki elemanlarını bize versin.
# Hadi yapalım:

MatrixListe[:,1]

array([2, 5, 8])

In [44]:
# Bu kadar basit

## Mantıksal operasyonlar

### Büyüktür ve Küçüktür operatörleri

In [56]:
# Şimdi mantıksal işlemler yapalım. Rastgele sayılardan oluşan tek boyutlu bir liste olsun ve bu listede 7'den büyük sayıları bulalım.

Liste = np.random.randint(1,14,10)
Liste

array([ 3, 12,  9,  7, 10,  8,  5,  6,  8,  2])

In [57]:
Liste > 7

array([False,  True,  True, False,  True,  True, False, False,  True,
       False])

In [58]:
# 7'den büyük sayılar True, diğerleri ise False olarak gösterildi
# Şimdi de 7'den küçük olanlara bakalım

Liste < 7

array([ True, False, False, False, False, False,  True,  True, False,
        True])

In [59]:
# Bu seferde tam tersini yaptık.

### Eşittir operatörü

In [60]:
# Bu sefer sadece 7 olanları alalım

Liste == 7

array([False, False, False,  True, False, False, False, False, False,
       False])

In [61]:
# Sadece 3.index'de ki eleman 7 olduğu görünüyor. Bir bakalım
Liste[3]

7

In [64]:
# Şimdi de 7'den büyük sayıları True False olarak değilde sadece oldukları gibi görelim.
# Bunun için şunu yaparız:

Liste_yedidenBuyukler = Liste > 7 # 7'den büyük olanların True False olarak yazan o listeyi bir değişkene atadık

Liste[Liste_yedidenBuyukler] 

array([12,  9, 10,  8,  8])

In [65]:
# İndex çağırma alanına True ve False olan listeyi verdik ve bize True ile işaretli indexleri verdi.
# Bu sayede filtreleme algoritmaları yazabilirsiniz.

### Aritmetik operatörler

In [66]:
# Listeler arası toplama, çarpma, bölme gibi işlemleri yapabilirsiniz

Liste = np.arange(0,24)
Liste

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
Liste + Liste # Bütün elemanları kendisi ile topla

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [68]:
Liste * Liste # Kendisi ile çarp

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [69]:
Liste - Liste # Kendisi ile çıkart

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [70]:
Liste / Liste # Ve kendisi ile böl

C:\Users\yigit\AppData\Local\Temp\ipykernel_12448\2246754809.py:1: RuntimeWarning: invalid value encountered in divide
  Liste / Liste # Ve kendisi ile böl


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
# opss arada sıfır kaynadı
Liste[1:] / Liste[1:]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

# Kapanış
<p>Tebrikler! Artık NumPy kütüphanesinin temellerini öğrendiniz ve veri bilimine giriş yaptınız. 
Ama bu kütüphane veri bilimi için yeterli değildir, bu sadece başlangıç. Bu kütüphane veri biliminin temeli olsa da tek başına yeterli değildir.</p>